---

language: go

go:
  - 1.7.x
  - master

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

install:
  - make dependencies

script:
  - make test
  - make benchmark
  - make build
